/* tslint:disable */
/* eslint-disable */
/**
 * MyAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 * M:ExampleWebApp.Backend.WebApi.AuthController.CurrentUser api response data.
 * @export
 * @interface CurrentUserResponseDto
 */
export interface CurrentUserResponseDto {
    /**
     * 
     * @type {CurrentUserStatus}
     * @memberof CurrentUserResponseDto
     */
    'status'?: CurrentUserStatus;
    /**
     * Login username.
     * @type {string}
     * @memberof CurrentUserResponseDto
     */
    'userName'?: string | null;
    /**
     * Email address.
     * @type {string}
     * @memberof CurrentUserResponseDto
     */
    'email'?: string | null;
    /**
     * List of roles associated to this user.
     * @type {Array<string>}
     * @memberof CurrentUserResponseDto
     */
    'roles'?: Array<string> | null;
}


/**
 * M:ExampleWebApp.Backend.WebApi.AuthController.CurrentUser response api specific status.  0 = OK  2 = InvalidArgument  3 = InvalidAuthentication  100 = AccessTokenNotFound
 * @export
 * @enum {string}
 */

export const CurrentUserStatus = {
    /**
    * 
    */
    OK: 0,
    /**
    * 
    */
    InvalidArgument: 2,
    /**
    * 
    */
    InvalidAuthentication: 3,
    /**
    * 
    */
    AccessTokenNotFound: 100
} as const;

export type CurrentUserStatus = typeof CurrentUserStatus[keyof typeof CurrentUserStatus];


/**
 * 
 * @export
 * @interface IdentityError
 */
export interface IdentityError {
    /**
     * 
     * @type {string}
     * @memberof IdentityError
     */
    'code'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IdentityError
     */
    'description'?: string | null;
}
/**
 * M:ExampleWebApp.Backend.WebApi.AuthController.LockoutUser(ExampleWebApp.Backend.WebApi.LockoutUserRequestDto) api request data.
 * @export
 * @interface LockoutUserRequestDto
 */
export interface LockoutUserRequestDto {
    /**
     * User name.
     * @type {string}
     * @memberof LockoutUserRequestDto
     */
    'userName'?: string | null;
    /**
     * Lock out end (UTC).
     * @type {string}
     * @memberof LockoutUserRequestDto
     */
    'lockoutEnd'?: string;
}
/**
 * M:ExampleWebApp.Backend.WebApi.AuthController.Login(ExampleWebApp.Backend.WebApi.LoginRequestDto) api request data.
 * @export
 * @interface LoginRequestDto
 */
export interface LoginRequestDto {
    /**
     * Username. If null but ExampleWebApp.Backend.WebApi.LoginRequestDto.Email was given login will be tried within email as user identifier, instead of the username.
     * @type {string}
     * @memberof LoginRequestDto
     */
    'userName'?: string | null;
    /**
     * Email. Can be null if non null ExampleWebApp.Backend.WebApi.LoginRequestDto.UserName given.
     * @type {string}
     * @memberof LoginRequestDto
     */
    'email'?: string | null;
    /**
     * Password.
     * @type {string}
     * @memberof LoginRequestDto
     */
    'password'?: string | null;
}
/**
 * M:ExampleWebApp.Backend.WebApi.AuthController.Login(ExampleWebApp.Backend.WebApi.LoginRequestDto) api response data.
 * @export
 * @interface LoginResponseDto
 */
export interface LoginResponseDto {
    /**
     * 
     * @type {LoginStatus}
     * @memberof LoginResponseDto
     */
    'status'?: LoginStatus;
    /**
     * Username.
     * @type {string}
     * @memberof LoginResponseDto
     */
    'userName'?: string | null;
    /**
     * Email.
     * @type {string}
     * @memberof LoginResponseDto
     */
    'email'?: string | null;
    /**
     * User roles.
     * @type {Array<string>}
     * @memberof LoginResponseDto
     */
    'roles'?: Array<string> | null;
}


/**
 * M:ExampleWebApp.Backend.WebApi.AuthController.Login(ExampleWebApp.Backend.WebApi.LoginRequestDto) response api specific status.  0 = OK  2 = UsernameOrEmailRequired  3 = InvalidAuthentication  8 = InvalidHttpContext
 * @export
 * @enum {string}
 */

export const LoginStatus = {
    /**
    * 
    */
    OK: 0,
    /**
    * 
    */
    UsernameOrEmailRequired: 2,
    /**
    * 
    */
    InvalidAuthentication: 3,
    /**
    * 
    */
    InvalidHttpContext: 8
} as const;

export type LoginStatus = typeof LoginStatus[keyof typeof LoginStatus];


/**
 * M:ExampleWebApp.Backend.WebApi.AuthController.RegisterUser(ExampleWebApp.Backend.WebApi.RegisterUserRequestDto) api request data.
 * @export
 * @interface RegisterUserRequestDto
 */
export interface RegisterUserRequestDto {
    /**
     * User name.
     * @type {string}
     * @memberof RegisterUserRequestDto
     */
    'userName'?: string | null;
    /**
     * User email.
     * @type {string}
     * @memberof RegisterUserRequestDto
     */
    'email'?: string | null;
    /**
     * User password.
     * @type {string}
     * @memberof RegisterUserRequestDto
     */
    'password'?: string | null;
}
/**
 * M:ExampleWebApp.Backend.WebApi.AuthController.RegisterUser(ExampleWebApp.Backend.WebApi.RegisterUserRequestDto) api response data.
 * @export
 * @interface RegisterUserResponseDto
 */
export interface RegisterUserResponseDto {
    /**
     * 
     * @type {RegisterUserStatus}
     * @memberof RegisterUserResponseDto
     */
    'status'?: RegisterUserStatus;
    /**
     * List of register errors if any.
     * @type {Array<IdentityError>}
     * @memberof RegisterUserResponseDto
     */
    'errors'?: Array<IdentityError> | null;
}


/**
 * M:ExampleWebApp.Backend.WebApi.AuthController.RegisterUser(ExampleWebApp.Backend.WebApi.RegisterUserRequestDto) response api specific status.  0 = OK  5 = IdentityError
 * @export
 * @enum {string}
 */

export const RegisterUserStatus = {
    /**
    * 
    */
    OK: 0,
    /**
    * 
    */
    IdentityError: 5
} as const;

export type RegisterUserStatus = typeof RegisterUserStatus[keyof typeof RegisterUserStatus];


/**
 * M:ExampleWebApp.Backend.WebApi.AuthController.SetUserRoles(ExampleWebApp.Backend.WebApi.SetUserRolesRequestDto) api request data.
 * @export
 * @interface SetUserRolesRequestDto
 */
export interface SetUserRolesRequestDto {
    /**
     * User name.
     * @type {string}
     * @memberof SetUserRolesRequestDto
     */
    'userName'?: string | null;
    /**
     * Roles to set to the user.
     * @type {Array<string>}
     * @memberof SetUserRolesRequestDto
     */
    'roles'?: Array<string> | null;
}
/**
 * M:ExampleWebApp.Backend.WebApi.AuthController.SetUserRoles(ExampleWebApp.Backend.WebApi.SetUserRolesRequestDto) api response data.
 * @export
 * @interface SetUserRolesResponseDto
 */
export interface SetUserRolesResponseDto {
    /**
     * 
     * @type {SetUserRolesStatus}
     * @memberof SetUserRolesResponseDto
     */
    'status'?: SetUserRolesStatus;
    /**
     * Roles added.
     * @type {Array<string>}
     * @memberof SetUserRolesResponseDto
     */
    'rolesAdded'?: Array<string> | null;
    /**
     * Roles removed.
     * @type {Array<string>}
     * @memberof SetUserRolesResponseDto
     */
    'rolesRemoved'?: Array<string> | null;
}


/**
 * M:ExampleWebApp.Backend.WebApi.AuthController.SetUserRoles(ExampleWebApp.Backend.WebApi.SetUserRolesRequestDto) response api specific status.  0 = OK  1 = InternalError  6 = AdminRolesReadOnly  7 = UserNotFound
 * @export
 * @enum {string}
 */

export const SetUserRolesStatus = {
    /**
    * 
    */
    OK: 0,
    /**
    * 
    */
    InternalError: 1,
    /**
    * 
    */
    AdminRolesReadOnly: 6,
    /**
    * 
    */
    UserNotFound: 7
} as const;

export type SetUserRolesStatus = typeof SetUserRolesStatus[keyof typeof SetUserRolesStatus];


/**
 * M:ExampleWebApp.Backend.WebApi.AuthController.ListUsers api response data.
 * @export
 * @interface UserListItemResponseDto
 */
export interface UserListItemResponseDto {
    /**
     * User name.
     * @type {string}
     * @memberof UserListItemResponseDto
     */
    'userName'?: string | null;
    /**
     * User email.
     * @type {string}
     * @memberof UserListItemResponseDto
     */
    'email'?: string | null;
    /**
     * User roles.
     * @type {Array<string>}
     * @memberof UserListItemResponseDto
     */
    'roles'?: Array<string> | null;
    /**
     * Access failed count.
     * @type {number}
     * @memberof UserListItemResponseDto
     */
    'accessFailedCount'?: number;
    /**
     * Email is confirmed.
     * @type {boolean}
     * @memberof UserListItemResponseDto
     */
    'emailConfirmed'?: boolean;
    /**
     * Lockout end (UTC).
     * @type {string}
     * @memberof UserListItemResponseDto
     */
    'lockoutEnd'?: string | null;
    /**
     * User phone number.
     * @type {string}
     * @memberof UserListItemResponseDto
     */
    'phoneNumber'?: string | null;
    /**
     * User phone number confirmed.
     * @type {boolean}
     * @memberof UserListItemResponseDto
     */
    'phoneNumberConfirmed'?: boolean;
    /**
     * Two factor enabled.
     * @type {boolean}
     * @memberof UserListItemResponseDto
     */
    'twoFactorEnabled'?: boolean;
}

/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Retrieve current logged in user name, email, roles.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        currentUser: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Auth/CurrentUser`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List all roles.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listRoles: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Auth/ListRoles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List all users.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listUsers: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Auth/ListUsers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Immediate user lockout until given time or unlock if time is in the past ( UTC ).  Note that this happens when access token expires.
         * @param {LockoutUserRequestDto} [lockoutUserRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        lockoutUser: async (lockoutUserRequestDto?: LockoutUserRequestDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Auth/LockoutUser`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(lockoutUserRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Login user by given username or email and auth password.
         * @param {LoginRequestDto} [loginRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login: async (loginRequestDto?: LoginRequestDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Auth/Login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Logout current user.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logout: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Auth/Logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create user by given username, email, password.
         * @param {RegisterUserRequestDto} [registerUserRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerUser: async (registerUserRequestDto?: RegisterUserRequestDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Auth/RegisterUser`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(registerUserRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Change user roles
         * @param {SetUserRolesRequestDto} [setUserRolesRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setUserRoles: async (setUserRolesRequestDto?: SetUserRolesRequestDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Auth/SetUserRoles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(setUserRolesRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Retrieve current logged in user name, email, roles.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async currentUser(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CurrentUserResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.currentUser(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary List all roles.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listRoles(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<string>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listRoles(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary List all users.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listUsers(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<UserListItemResponseDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listUsers(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Immediate user lockout until given time or unlock if time is in the past ( UTC ).  Note that this happens when access token expires.
         * @param {LockoutUserRequestDto} [lockoutUserRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async lockoutUser(lockoutUserRequestDto?: LockoutUserRequestDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.lockoutUser(lockoutUserRequestDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Login user by given username or email and auth password.
         * @param {LoginRequestDto} [loginRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async login(loginRequestDto?: LoginRequestDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LoginResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.login(loginRequestDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Logout current user.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async logout(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.logout(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Create user by given username, email, password.
         * @param {RegisterUserRequestDto} [registerUserRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerUser(registerUserRequestDto?: RegisterUserRequestDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RegisterUserResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.registerUser(registerUserRequestDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Change user roles
         * @param {SetUserRolesRequestDto} [setUserRolesRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async setUserRoles(setUserRolesRequestDto?: SetUserRolesRequestDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SetUserRolesResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.setUserRoles(setUserRolesRequestDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * 
         * @summary Retrieve current logged in user name, email, roles.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        currentUser(options?: any): AxiosPromise<CurrentUserResponseDto> {
            return localVarFp.currentUser(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List all roles.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listRoles(options?: any): AxiosPromise<Array<string>> {
            return localVarFp.listRoles(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List all users.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listUsers(options?: any): AxiosPromise<Array<UserListItemResponseDto>> {
            return localVarFp.listUsers(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Immediate user lockout until given time or unlock if time is in the past ( UTC ).  Note that this happens when access token expires.
         * @param {LockoutUserRequestDto} [lockoutUserRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        lockoutUser(lockoutUserRequestDto?: LockoutUserRequestDto, options?: any): AxiosPromise<void> {
            return localVarFp.lockoutUser(lockoutUserRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Login user by given username or email and auth password.
         * @param {LoginRequestDto} [loginRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login(loginRequestDto?: LoginRequestDto, options?: any): AxiosPromise<LoginResponseDto> {
            return localVarFp.login(loginRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Logout current user.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logout(options?: any): AxiosPromise<void> {
            return localVarFp.logout(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create user by given username, email, password.
         * @param {RegisterUserRequestDto} [registerUserRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerUser(registerUserRequestDto?: RegisterUserRequestDto, options?: any): AxiosPromise<RegisterUserResponseDto> {
            return localVarFp.registerUser(registerUserRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Change user roles
         * @param {SetUserRolesRequestDto} [setUserRolesRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setUserRoles(setUserRolesRequestDto?: SetUserRolesRequestDto, options?: any): AxiosPromise<SetUserRolesResponseDto> {
            return localVarFp.setUserRoles(setUserRolesRequestDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI {
    /**
     * 
     * @summary Retrieve current logged in user name, email, roles.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public currentUser(options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).currentUser(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List all roles.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public listRoles(options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).listRoles(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List all users.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public listUsers(options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).listUsers(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Immediate user lockout until given time or unlock if time is in the past ( UTC ).  Note that this happens when access token expires.
     * @param {LockoutUserRequestDto} [lockoutUserRequestDto] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public lockoutUser(lockoutUserRequestDto?: LockoutUserRequestDto, options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).lockoutUser(lockoutUserRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Login user by given username or email and auth password.
     * @param {LoginRequestDto} [loginRequestDto] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public login(loginRequestDto?: LoginRequestDto, options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).login(loginRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Logout current user.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public logout(options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).logout(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create user by given username, email, password.
     * @param {RegisterUserRequestDto} [registerUserRequestDto] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public registerUser(registerUserRequestDto?: RegisterUserRequestDto, options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).registerUser(registerUserRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Change user roles
     * @param {SetUserRolesRequestDto} [setUserRolesRequestDto] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public setUserRoles(setUserRolesRequestDto?: SetUserRolesRequestDto, options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).setUserRoles(setUserRolesRequestDto, options).then((request) => request(this.axios, this.basePath));
    }
}



